apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    role: app 
spec:
  replicas: 3
  selector:
    matchLabels:
      role: app 
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: webapp
        image: nginx:latest
        ports:
        - containerPort: 80
