apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    role: app 
spec:
  replicas: 2
  selector:
    matchLabels:
      role: app 
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: webapp
        image: poojansds/webapp:v1
        ports:
        - containerPort: 80
